### ISSUE TITLE
assemble.sh failed

### ISSUE THREAD

**Issue by MirrorDM** [hammacher/javaslicer#4]
Seems that some files are missing on http://titania.fs.uni-saarland.de/nexus/content/groups/public 
Here is the error message:

Found 6 projects:
  - .
  - javaslicer-common
  - javaslicer-core (with assembly)
  - javaslicer-jung (with assembly)
  - javaslicer-traceReader (with assembly)
  - javaslicer-tracer (with assembly)

Pass 1: run clean and install on all projects iteratively, until all succeed:
  - ....  success
  - javaslicer-common...  failure
  - javaslicer-core...  failure
  - javaslicer-jung...  failure
  - javaslicer-traceReader...  failure
  - javaslicer-tracer...  failure
  - javaslicer-common...  failure
  - javaslicer-core...  failure
  - javaslicer-jung...  failure
  - javaslicer-traceReader...  failure
  - javaslicer-tracer...  failure
Error: No more progress, exiting!
Components with errors:
  - javaslicer-common
  - javaslicer-core
  - javaslicer-jung
  - javaslicer-traceReader
  - javaslicer-tracer

Last error output:
[INFO] Scanning for projects...
[INFO]                                                                         
[INFO] ------------------------------------------------------------------------
[INFO] Building JAVASLICER Tracing Component 1.1.1-SNAPSHOT
[INFO] ------------------------------------------------------------------------
[WARNING] The POM for de.unisb.cs.st:javaslicer-common:jar:1.1.1-SNAPSHOT is missing, no dependency information available
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 0.950 s
[INFO] Finished at: 2016-10-18T01:31:34-07:00
[INFO] Final Memory: 8M/105M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal on project javaslicer-tracer: Could not resolve dependencies for project de.unisb.cs.st:javaslicer-tracer:jar:1.1.1-SNAPSHOT: Failure to find de.unisb.cs.st:javaslicer-common:jar:1.1.1-SNAPSHOT in http://titania.fs.uni-saarland.de/nexus/content/groups/public was cached in the local repository, resolution will not be reattempted until the update interval of titania has elapsed or updates are forced -> [Help 1]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/DependencyResolutionException

**Comment by MirrorDM** [comment]
Java version: 1.7.0_79
Maven version: 3.3.9

Fix: 
Run `git checkout e2235b1` before `./assemble.sh`, which is the last commit for Java 7.

Suggestion:
Publish some release versions if possible.

**Comment by BenediktEberhardinger** [comment]
That fix doesn't work with my installation. 
Java version: 1.7.0_79
Maven version: 3.3.9
on Ubuntu 16.10

I still got the following failures:
Found 6 projects:
  - .
  - javaslicer-common
  - javaslicer-core (with assembly)
  - javaslicer-jung (with assembly)
  - javaslicer-traceReader (with assembly)
  - javaslicer-tracer (with assembly)

Pass 1: run clean and install on all projects iteratively, until all succeed:
  - ....  success
  - javaslicer-common...  failure
  - javaslicer-core...  failure
  - javaslicer-jung...  failure
  - javaslicer-traceReader...  failure
  - javaslicer-tracer...  failure
  - javaslicer-common...  failure
  - javaslicer-core...  failure
  - javaslicer-jung...  failure
  - javaslicer-traceReader...  failure
  - javaslicer-tracer...  failure
Error: No more progress, exiting!
Components with errors:
  - javaslicer-common
  - javaslicer-core
  - javaslicer-jung
  - javaslicer-traceReader
  - javaslicer-tracer

Last error output:
[INFO] Scanning for projects...
[INFO]                                                                         
[INFO] ------------------------------------------------------------------------
[INFO] Building JAVASLICER Tracing Component 1.1.1-SNAPSHOT
[INFO] ------------------------------------------------------------------------
[WARNING] The POM for de.unisb.cs.st:javaslicer-common:jar:1.1.1-SNAPSHOT is missing, no dependency information available
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 1.318 s
[INFO] Finished at: 2016-12-05T10:30:52+01:00
[INFO] Final Memory: 8M/30M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal on project javaslicer-tracer: Could not resolve dependencies for project de.unisb.cs.st:javaslicer-tracer:jar:1.1.1-SNAPSHOT: Failure to find de.unisb.cs.st:javaslicer-common:jar:1.1.1-SNAPSHOT in http://titania.fs.uni-saarland.de/nexus/content/groups/public was cached in the local repository, resolution will not be reattempted until the update interval of titania has elapsed or updates are forced -> [Help 1]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/DependencyResolutionException

**Comment by BenediktEberhardinger** [comment]
Fixed.
Build first with Maven in Eclipse and afterwards run the Shellscript.
Somehow, that worked for me.

**Comment by msintaha** [comment]
@backes Hi! is it possible to fix the issue? I'm running on MacOS High Sierra and tried with both Java 1.6 and 1.7 (with maven 3.2 and 3.3 respectively) but the `./assemble.sh` script is still failing. I tried in master branch and even checked out to the branch as suggested in one of the comments here, but still getting failures in the script.

```
Found 6 projects:
  - .
  - javaslicer-common
  - javaslicer-core (with assembly)
  - javaslicer-jung (with assembly)
  - javaslicer-traceReader (with assembly)
  - javaslicer-tracer (with assembly)

Pass 1: run clean and install on all projects iteratively, until all succeed:
  - ....  success
  - javaslicer-common...  failure
  - javaslicer-core...  failure
  - javaslicer-jung...  failure
  - javaslicer-traceReader...  failure
  - javaslicer-tracer...  failure
  - javaslicer-common...  failure
  - javaslicer-core...  failure
  - javaslicer-jung...  failure
  - javaslicer-traceReader...  failure
  - javaslicer-tracer...  failure
Error: No more progress, exiting!
Components with errors:
  - javaslicer-common
  - javaslicer-core
  - javaslicer-jung
  - javaslicer-traceReader
  - javaslicer-tracer

Last error output:
[INFO] Scanning for projects...
[INFO]                                                                         
[INFO] ------------------------------------------------------------------------
[INFO] Building JAVASLICER Tracing Component 1.1.1-SNAPSHOT
[INFO] ------------------------------------------------------------------------
[WARNING] The POM for de.unisb.cs.st:javaslicer-common:jar:1.1.1-SNAPSHOT is missing, no dependency information available
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 0.235 s
[INFO] Finished at: 2021-04-02T12:53:14+06:00
[INFO] Final Memory: 10M/60M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal on project javaslicer-tracer: Could not resolve dependencies for project de.unisb.cs.st:javaslicer-tracer:jar:1.1.1-SNAPSHOT: Failure to find de.unisb.cs.st:javaslicer-common:jar:1.1.1-SNAPSHOT in http://titania.fs.uni-saarland.de/nexus/content/groups/public was cached in the local repository, resolution will not be reattempted until the update interval of titania has elapsed or updates are forced -> [Help 1]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/DependencyResolutionException
```
